CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_id varchar(100) UNIQUE not null,
    name varchar(100) not null,
    email varchar(100) UNIQUE not null,
    phone varchar(100) UNIQUE,
    address varchar(100) not null,
    age integer,
    gender TINYINT,
    avatar varchar(500),
    created_date timestamp,
    updated_date timestamp,
);